void triangle_functions(int fill_type, int shape_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void arrow_functions (int fill_type, int shape_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void chatbox_function(char borderColor, char symbol, int size, int position_choice);
void diamond_function(int fill_type, int shape_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void heart_functions(int fill_type, int shape_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void hexagon_functions(int fill_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void line_functions(int shape_type, char color, char symbol, int size, int position_choice);
void paralellogram_functions(int fill_type, int shape_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void pentagon_functions(int fill_type, int shape_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void reactangle_functions(int fill_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void rhombus_functions(int fill_type, int shape_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void rightangledtriangle_functions(int fill_type, int shape_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void square_functions(int fill_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void star_functions(int fill_type, int shape_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void trapezium_functions(int fill_type, int shape_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void circle_function(int fill_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void butterfly_functions(int fill_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void house_functions(int fill_type, int shape_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void octagon_functions(int fill_type, char borderColor, char fillColor, char symbol, int size, int position_choice);
void freehand_drawing_functions(char symbol, char color);